In [83]:
import subprocess
import ast


In [81]:
def load_config(config_file):
    with open(config_file, 'r') as file:
        return yaml.safe_load(file)

In [92]:
def run_script_and_capture_output(script_name):
    # Backup the original globals
    old_globals = globals().copy()

    # Run the script and capture the outputs
    %run -i $script_name

    # Extract the outputs from the globals after running the script
    model_dict_fc = globals().get('model_dict_fc')
    model_dict_sparse = globals().get('model_dict_sparse')

    # Restore the original globals to avoid polluting the notebook environment
    globals().update(old_globals)

    return model_dict_fc, model_dict_sparse

# Run the script and capture the outputs
model_dict_fc, model_dict_sparse = run_script_and_capture_output('custom_main.py')

# Now you can use model_dict_fc and model_dict_sparse in your notebook
print(model_dict_sparse)

Getting Marker Genes.......
1125
1125
2250
2250
                    0                1
0     ENSG00000101210  ENSG00000172270
1     ENSG00000099622  ENSG00000141905
2     ENSG00000105278  ENSG00000167658
3     ENSG00000178951  ENSG00000089847
4     ENSG00000141985  ENSG00000127663
...               ...              ...
1120  ENSG00000285395  ENSG00000103316
1121  ENSG00000140740  ENSG00000284218
1122  ENSG00000122254  ENSG00000103365
1123  ENSG00000006116  ENSG00000182601
1124  ENSG00000077235  ENSG00000171208

[1125 rows x 2 columns]
                    0                1
0     ENSG00000101210  ENSG00000172270
1     ENSG00000099622  ENSG00000141905
2     ENSG00000105278  ENSG00000167658
3     ENSG00000178951  ENSG00000089847
4     ENSG00000141985  ENSG00000127663
...               ...              ...
1120  ENSG00000285395  ENSG00000103316
1121  ENSG00000140740  ENSG00000284218
1122  ENSG00000122254  ENSG00000103365
1123  ENSG00000006116  ENSG00000182601
1124  ENSG00000077235  ENSG000

/home/anwer/.local/lib/python3.12/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "


Training.........
Current sub-neural network has 1 hidden layers.
...


  2%|███▍                                                                                                                                                                         | 1/50 [00:00<00:15,  3.08it/s]

Epoch [1/50], Train Loss: 5.0317, Train_accuracy: 49.82605608803692, Val Loss: 2.1583, Val_accuracy: 50.24494142705005
Model saved.


  4%|██████▉                                                                                                                                                                      | 2/50 [00:00<00:15,  3.06it/s]

Epoch [2/50], Train Loss: 4.9790, Train_accuracy: 49.82605608803692, Val Loss: 2.1352, Val_accuracy: 50.24494142705005


  6%|██████████▍                                                                                                                                                                  | 3/50 [00:01<00:21,  2.20it/s]

Epoch [3/50], Train Loss: 4.9351, Train_accuracy: 49.82605608803692, Val Loss: 2.1158, Val_accuracy: 50.24494142705005


  8%|█████████████▊                                                                                                                                                               | 4/50 [00:01<00:18,  2.45it/s]

Epoch [4/50], Train Loss: 4.9051, Train_accuracy: 49.82605608803692, Val Loss: 2.1025, Val_accuracy: 50.24494142705005


 10%|█████████████████▎                                                                                                                                                           | 5/50 [00:02<00:21,  2.08it/s]

Epoch [5/50], Train Loss: 4.8874, Train_accuracy: 49.82605608803692, Val Loss: 2.0947, Val_accuracy: 50.24494142705005


 12%|████████████████████▊                                                                                                                                                        | 6/50 [00:02<00:18,  2.33it/s]

Epoch [6/50], Train Loss: 4.8771, Train_accuracy: 49.82605608803692, Val Loss: 2.0903, Val_accuracy: 50.24494142705005


 14%|████████████████████████▏                                                                                                                                                    | 7/50 [00:03<00:20,  2.05it/s]

Epoch [7/50], Train Loss: 4.8707, Train_accuracy: 49.82605608803692, Val Loss: 2.0875, Val_accuracy: 50.24494142705005


 16%|███████████████████████████▋                                                                                                                                                 | 8/50 [00:03<00:18,  2.29it/s]

Epoch [8/50], Train Loss: 4.8666, Train_accuracy: 49.82605608803692, Val Loss: 2.0858, Val_accuracy: 50.24494142705005


 18%|███████████████████████████████▏                                                                                                                                             | 9/50 [00:03<00:16,  2.48it/s]

Epoch [9/50], Train Loss: 4.8637, Train_accuracy: 49.82605608803692, Val Loss: 2.0846, Val_accuracy: 50.24494142705005


 20%|██████████████████████████████████▍                                                                                                                                         | 10/50 [00:04<00:18,  2.17it/s]

Epoch [10/50], Train Loss: 4.8617, Train_accuracy: 49.82605608803692, Val Loss: 2.0837, Val_accuracy: 50.24494142705005


 22%|█████████████████████████████████████▊                                                                                                                                      | 11/50 [00:04<00:16,  2.36it/s]

Epoch [11/50], Train Loss: 4.8601, Train_accuracy: 49.82605608803692, Val Loss: 2.0831, Val_accuracy: 50.24494142705005


 24%|█████████████████████████████████████████▎                                                                                                                                  | 12/50 [00:05<00:18,  2.09it/s]

Epoch [12/50], Train Loss: 4.8589, Train_accuracy: 49.82605608803692, Val Loss: 2.0825, Val_accuracy: 50.24494142705005


 26%|████████████████████████████████████████████▋                                                                                                                               | 13/50 [00:05<00:16,  2.30it/s]

Epoch [13/50], Train Loss: 4.8579, Train_accuracy: 49.82605608803692, Val Loss: 2.0821, Val_accuracy: 50.24494142705005


 28%|████████████████████████████████████████████████▏                                                                                                                           | 14/50 [00:06<00:17,  2.04it/s]

Epoch [14/50], Train Loss: 4.8570, Train_accuracy: 49.82605608803692, Val Loss: 2.0818, Val_accuracy: 50.24494142705005


 30%|███████████████████████████████████████████████████▌                                                                                                                        | 15/50 [00:06<00:15,  2.26it/s]

Epoch [15/50], Train Loss: 4.8563, Train_accuracy: 49.82605608803692, Val Loss: 2.0815, Val_accuracy: 50.24494142705005


 32%|███████████████████████████████████████████████████████                                                                                                                     | 16/50 [00:06<00:13,  2.45it/s]

Epoch [16/50], Train Loss: 4.8556, Train_accuracy: 49.82605608803692, Val Loss: 2.0812, Val_accuracy: 50.24494142705005


 34%|██████████████████████████████████████████████████████████▍                                                                                                                 | 17/50 [00:07<00:15,  2.14it/s]

Epoch [17/50], Train Loss: 4.8550, Train_accuracy: 49.82605608803692, Val Loss: 2.0810, Val_accuracy: 50.24494142705005


 36%|█████████████████████████████████████████████████████████████▉                                                                                                              | 18/50 [00:07<00:13,  2.34it/s]

Epoch [18/50], Train Loss: 4.8544, Train_accuracy: 49.82605608803692, Val Loss: 2.0807, Val_accuracy: 50.24494142705005


 38%|█████████████████████████████████████████████████████████████████▎                                                                                                          | 19/50 [00:08<00:14,  2.07it/s]

Epoch [19/50], Train Loss: 4.8538, Train_accuracy: 49.82605608803692, Val Loss: 2.0805, Val_accuracy: 50.24494142705005


 40%|████████████████████████████████████████████████████████████████████▊                                                                                                       | 20/50 [00:08<00:13,  2.27it/s]

Epoch [20/50], Train Loss: 4.8531, Train_accuracy: 49.82605608803692, Val Loss: 2.0802, Val_accuracy: 50.24494142705005


 42%|████████████████████████████████████████████████████████████████████████▏                                                                                                   | 21/50 [00:09<00:11,  2.46it/s]

Epoch [21/50], Train Loss: 4.8522, Train_accuracy: 49.82605608803692, Val Loss: 2.0799, Val_accuracy: 50.24494142705005


 44%|███████████████████████████████████████████████████████████████████████████▋                                                                                                | 22/50 [00:09<00:13,  2.13it/s]

Epoch [22/50], Train Loss: 4.8511, Train_accuracy: 49.82605608803692, Val Loss: 2.0795, Val_accuracy: 50.24494142705005


 46%|███████████████████████████████████████████████████████████████████████████████                                                                                             | 23/50 [00:10<00:11,  2.33it/s]

Epoch [23/50], Train Loss: 4.8495, Train_accuracy: 49.82605608803692, Val Loss: 2.0789, Val_accuracy: 50.24494142705005


 48%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                         | 24/50 [00:10<00:10,  2.49it/s]

Epoch [24/50], Train Loss: 4.8470, Train_accuracy: 49.82605608803692, Val Loss: 2.0780, Val_accuracy: 50.24494142705005


 50%|██████████████████████████████████████████████████████████████████████████████████████                                                                                      | 25/50 [00:11<00:11,  2.14it/s]

Epoch [25/50], Train Loss: 4.8429, Train_accuracy: 49.82605608803692, Val Loss: 2.0764, Val_accuracy: 50.24494142705005


 52%|█████████████████████████████████████████████████████████████████████████████████████████▍                                                                                  | 26/50 [00:11<00:10,  2.34it/s]

Epoch [26/50], Train Loss: 4.8359, Train_accuracy: 49.82605608803692, Val Loss: 2.0736, Val_accuracy: 50.24494142705005


 54%|████████████████████████████████████████████████████████████████████████████████████████████▉                                                                               | 27/50 [00:11<00:09,  2.50it/s]

Epoch [27/50], Train Loss: 4.8255, Train_accuracy: 49.82605608803692, Val Loss: 2.0695, Val_accuracy: 50.24494142705005


 56%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                           | 28/50 [00:12<00:10,  2.14it/s]

Epoch [28/50], Train Loss: 4.8123, Train_accuracy: 49.82605608803692, Val Loss: 2.0642, Val_accuracy: 50.24494142705005


 58%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                        | 29/50 [00:12<00:08,  2.33it/s]

Epoch [29/50], Train Loss: 4.7981, Train_accuracy: 49.82605608803692, Val Loss: 2.0584, Val_accuracy: 50.24494142705005


 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                    | 30/50 [00:13<00:09,  2.08it/s]

Epoch [30/50], Train Loss: 4.7849, Train_accuracy: 49.82605608803692, Val Loss: 2.0530, Val_accuracy: 50.24494142705005


 62%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                 | 31/50 [00:13<00:08,  2.29it/s]

Epoch [31/50], Train Loss: 4.7732, Train_accuracy: 49.82605608803692, Val Loss: 2.0482, Val_accuracy: 50.24494142705005


 64%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                              | 32/50 [00:13<00:07,  2.46it/s]

Epoch [32/50], Train Loss: 4.7607, Train_accuracy: 49.82605608803692, Val Loss: 2.0431, Val_accuracy: 50.24494142705005


 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                          | 33/50 [00:14<00:07,  2.13it/s]

Epoch [33/50], Train Loss: 4.7477, Train_accuracy: 49.82605608803692, Val Loss: 2.0378, Val_accuracy: 50.24494142705005


 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                       | 34/50 [00:14<00:06,  2.33it/s]

Epoch [34/50], Train Loss: 4.7342, Train_accuracy: 49.82605608803692, Val Loss: 2.0323, Val_accuracy: 50.24494142705005


 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                   | 35/50 [00:15<00:07,  2.07it/s]

Epoch [35/50], Train Loss: 4.7200, Train_accuracy: 49.82605608803692, Val Loss: 2.0266, Val_accuracy: 50.24494142705005


 72%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                | 36/50 [00:15<00:06,  2.28it/s]

Epoch [36/50], Train Loss: 4.7051, Train_accuracy: 49.82605608803692, Val Loss: 2.0206, Val_accuracy: 50.24494142705005


 74%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                            | 37/50 [00:16<00:05,  2.45it/s]

Epoch [37/50], Train Loss: 4.6897, Train_accuracy: 49.82605608803692, Val Loss: 2.0143, Val_accuracy: 50.24494142705005


 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                         | 38/50 [00:16<00:05,  2.14it/s]

Epoch [38/50], Train Loss: 4.6739, Train_accuracy: 49.82605608803692, Val Loss: 2.0080, Val_accuracy: 50.24494142705005


 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 39/50 [00:17<00:04,  2.35it/s]

Epoch [39/50], Train Loss: 4.6579, Train_accuracy: 49.82605608803692, Val Loss: 2.0017, Val_accuracy: 50.24494142705005


 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 40/50 [00:17<00:04,  2.09it/s]

Epoch [40/50], Train Loss: 4.6417, Train_accuracy: 49.82605608803692, Val Loss: 1.9953, Val_accuracy: 50.24494142705005


 82%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 41/50 [00:18<00:03,  2.29it/s]

Epoch [41/50], Train Loss: 4.6255, Train_accuracy: 49.82605608803692, Val Loss: 1.9889, Val_accuracy: 50.24494142705005


 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                           | 42/50 [00:18<00:03,  2.01it/s]

Epoch [42/50], Train Loss: 4.6094, Train_accuracy: 49.82605608803692, Val Loss: 1.9826, Val_accuracy: 50.24494142705005


 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 43/50 [00:19<00:03,  2.20it/s]

Epoch [43/50], Train Loss: 4.5939, Train_accuracy: 49.82605608803692, Val Loss: 1.9766, Val_accuracy: 50.24494142705005


 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 44/50 [00:19<00:02,  2.39it/s]

Epoch [44/50], Train Loss: 4.5791, Train_accuracy: 49.82605608803692, Val Loss: 1.9710, Val_accuracy: 50.24494142705005


 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 45/50 [00:20<00:02,  2.11it/s]

Epoch [45/50], Train Loss: 4.5652, Train_accuracy: 49.82605608803692, Val Loss: 1.9656, Val_accuracy: 50.24494142705005


 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 46/50 [00:20<00:01,  2.32it/s]

Epoch [46/50], Train Loss: 4.5522, Train_accuracy: 49.82605608803692, Val Loss: 1.9606, Val_accuracy: 50.24494142705005


 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 47/50 [00:20<00:01,  2.07it/s]

Epoch [47/50], Train Loss: 4.5399, Train_accuracy: 49.82605608803692, Val Loss: 1.9560, Val_accuracy: 50.24494142705005


 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 48/50 [00:21<00:00,  2.28it/s]

Epoch [48/50], Train Loss: 4.5285, Train_accuracy: 49.82605608803692, Val Loss: 1.9516, Val_accuracy: 50.24494142705005


 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 49/50 [00:21<00:00,  2.46it/s]

Epoch [49/50], Train Loss: 4.5178, Train_accuracy: 49.82605608803692, Val Loss: 1.9475, Val_accuracy: 50.24494142705005


100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:22<00:00,  2.25it/s]

Epoch [50/50], Train Loss: 4.5077, Train_accuracy: 49.82605608803692, Val Loss: 1.9437, Val_accuracy: 50.24494142705005


Test Accucary 50.27683134582624
Current sub-neural network has 2 hidden layers.
...


  2%|███▍                                                                                                                                                                         | 1/50 [00:00<00:16,  3.01it/s]

Epoch [1/50], Train Loss: 5.0780, Train_accuracy: 49.82605608803692, Val Loss: 2.1786, Val_accuracy: 50.24494142705005
Model saved.


  4%|██████▉                                                                                                                                                                      | 2/50 [00:00<00:24,  1.99it/s]

Epoch [2/50], Train Loss: 5.0749, Train_accuracy: 49.82605608803692, Val Loss: 2.1772, Val_accuracy: 50.24494142705005


  6%|██████████▍                                                                                                                                                                  | 3/50 [00:01<00:20,  2.35it/s]

Epoch [3/50], Train Loss: 5.0708, Train_accuracy: 49.82605608803692, Val Loss: 2.1754, Val_accuracy: 50.24494142705005


  8%|█████████████▊                                                                                                                                                               | 4/50 [00:01<00:17,  2.56it/s]

Epoch [4/50], Train Loss: 5.0650, Train_accuracy: 49.82605608803692, Val Loss: 2.1729, Val_accuracy: 50.24494142705005


 10%|█████████████████▎                                                                                                                                                           | 5/50 [00:02<00:21,  2.12it/s]

Epoch [5/50], Train Loss: 5.0571, Train_accuracy: 49.82605608803692, Val Loss: 2.1695, Val_accuracy: 50.24494142705005


 12%|████████████████████▊                                                                                                                                                        | 6/50 [00:02<00:18,  2.35it/s]

Epoch [6/50], Train Loss: 5.0465, Train_accuracy: 49.82605608803692, Val Loss: 2.1648, Val_accuracy: 50.24494142705005


 14%|████████████████████████▏                                                                                                                                                    | 7/50 [00:03<00:20,  2.05it/s]

Epoch [7/50], Train Loss: 5.0326, Train_accuracy: 49.82605608803692, Val Loss: 2.1588, Val_accuracy: 50.24494142705005


 16%|███████████████████████████▋                                                                                                                                                 | 8/50 [00:03<00:18,  2.27it/s]

Epoch [8/50], Train Loss: 5.0152, Train_accuracy: 49.82605608803692, Val Loss: 2.1512, Val_accuracy: 50.24494142705005


 18%|███████████████████████████████▏                                                                                                                                             | 9/50 [00:03<00:16,  2.45it/s]

Epoch [9/50], Train Loss: 4.9947, Train_accuracy: 49.82605608803692, Val Loss: 2.1423, Val_accuracy: 50.24494142705005


 20%|██████████████████████████████████▍                                                                                                                                         | 10/50 [00:04<00:18,  2.11it/s]

Epoch [10/50], Train Loss: 4.9726, Train_accuracy: 49.82605608803692, Val Loss: 2.1325, Val_accuracy: 50.24494142705005


 22%|█████████████████████████████████████▊                                                                                                                                      | 11/50 [00:04<00:16,  2.31it/s]

Epoch [11/50], Train Loss: 4.9506, Train_accuracy: 49.82605608803692, Val Loss: 2.1229, Val_accuracy: 50.24494142705005


 24%|█████████████████████████████████████████▎                                                                                                                                  | 12/50 [00:05<00:17,  2.16it/s]

Epoch [12/50], Train Loss: 4.9308, Train_accuracy: 49.82605608803692, Val Loss: 2.1142, Val_accuracy: 50.24494142705005


KeyboardInterrupt: 

{2: CustomNetwork(
  (layers): ModuleList(
    (0): Linear(in_features=582, out_features=356, bias=False)
    (1): Linear(in_features=356, out_features=1, bias=True)
  )
), 3: CustomNetwork(
  (layers): ModuleList(
    (0): Linear(in_features=582, out_features=356, bias=False)
    (1): Linear(in_features=356, out_features=134, bias=False)
    (2): Linear(in_features=134, out_features=1, bias=True)
  )
), 4: CustomNetwork(
  (layers): ModuleList(
    (0): Linear(in_features=582, out_features=356, bias=False)
    (1): Linear(in_features=356, out_features=134, bias=False)
    (2): Linear(in_features=134, out_features=29, bias=False)
    (3): Linear(in_features=29, out_features=1, bias=True)
  )
)}


In [90]:
result

CompletedProcess(args=['python', 'custom_main.py'], returncode=0, stdout=b'Getting Marker Genes.......\n1125\n1125\n2250\n2250\n                    0                1\n0     ENSG00000101210  ENSG00000172270\n1     ENSG00000099622  ENSG00000141905\n2     ENSG00000105278  ENSG00000167658\n3     ENSG00000178951  ENSG00000089847\n4     ENSG00000141985  ENSG00000127663\n...               ...              ...\n1120  ENSG00000285395  ENSG00000103316\n1121  ENSG00000140740  ENSG00000284218\n1122  ENSG00000122254  ENSG00000103365\n1123  ENSG00000006116  ENSG00000182601\n1124  ENSG00000077235  ENSG00000171208\n\n[1125 rows x 2 columns]\n                    0                1\n0     ENSG00000101210  ENSG00000172270\n1     ENSG00000099622  ENSG00000141905\n2     ENSG00000105278  ENSG00000167658\n3     ENSG00000178951  ENSG00000089847\n4     ENSG00000141985  ENSG00000127663\n...               ...              ...\n1120  ENSG00000285395  ENSG00000103316\n1121  ENSG00000140740  ENSG00000284218\n1122 

In [56]:
config = load_config('model_save/excitory_neurons/Exc_L2-3_CBLN2_LINC02306/2024_07_30_06_05_37/config.yml')

In [57]:
config

{'dataset': {'test': '/12tb_dsk1/danish/Pytorch_Biologically_Informed_Neural_Network/Preprocessed_data/excitory_neurons/Exc_L2-3_CBLN2_LINC02306/test.csv',
  'train': '/12tb_dsk1/danish/Pytorch_Biologically_Informed_Neural_Network/Preprocessed_data/excitory_neurons/Exc_L2-3_CBLN2_LINC02306/train.csv',
  'val': '/12tb_dsk1/danish/Pytorch_Biologically_Informed_Neural_Network/Preprocessed_data/excitory_neurons/Exc_L2-3_CBLN2_LINC02306/val.csv',
  'y_test': '/12tb_dsk1/danish/Pytorch_Biologically_Informed_Neural_Network/Preprocessed_data/excitory_neurons/Exc_L2-3_CBLN2_LINC02306/y_test.csv',
  'y_train': '/12tb_dsk1/danish/Pytorch_Biologically_Informed_Neural_Network/Preprocessed_data/excitory_neurons/Exc_L2-3_CBLN2_LINC02306/y_train.csv',
  'y_val': '/12tb_dsk1/danish/Pytorch_Biologically_Informed_Neural_Network/Preprocessed_data/excitory_neurons/Exc_L2-3_CBLN2_LINC02306/y_val.csv'},
 'date_string': '2024_07_30_06_05_37',
 'gene_expression': {'highly_expressed_threshold': 0.95,
  'lowly_e

In [58]:
train = pd.read_csv(config['dataset']['train'],index_col=0)
test = pd.read_csv(config['dataset']['test'],index_col=0)

In [59]:
y_train = pd.read_csv(config['dataset']['y_train'])
y_test = pd.read_csv(config['dataset']['y_test'])

In [60]:
val = pd.read_csv(config['dataset']['val'],index_col=0)
y_val = pd.read_csv(config['dataset']['y_val'])


In [61]:
r_data_tmp = train.T
q_data_tmp = test.T
v_data_tmp = val.T
r_label_tmp = y_train

print('Getting Marker Genes.......')
train_x, test_x, val_x, train_y = get_expression(r_data_tmp,
                                                q_data_tmp,
                                                v_data_tmp,
                                                r_label_tmp,
                                                thrh=config['gene_expression']['highly_expressed_threshold'],
                                                thrl=config['gene_expression']['lowly_expressed_threshold'],
                                                normalization=config['gene_expression']['normalization'],
                                                marker=config['gene_expression']['marker'])


print('Getting Pathway Genes.........')
pathway_genes = get_gene_pathways(config['pathways_network']['ensemble_pathway_relation'], species=config['pathways_network']['species'])


print('Getting Masking.........')
masking, layers_node, train_x, test_x,val_x = get_masking(config['pathways_network']['pathway_names'],
                                                        pathway_genes,
                                                        config['pathways_network']['pathway_relation'],
                                                        train_x,
                                                        test_x,
                                                        val_x,
                                                        train_y,
                                                        config['pathways_network']['datatype'],
                                                        config['pathways_network']['species'],
                                                        config['pathways_network']['n_hidden_layer'])

Getting Marker Genes.......
1125
1125
2250
2250
                    0                1
0     ENSG00000101210  ENSG00000172270
1     ENSG00000099622  ENSG00000141905
2     ENSG00000105278  ENSG00000167658
3     ENSG00000178951  ENSG00000089847
4     ENSG00000141985  ENSG00000127663
...               ...              ...
1120  ENSG00000285395  ENSG00000103316
1121  ENSG00000140740  ENSG00000284218
1122  ENSG00000122254  ENSG00000103365
1123  ENSG00000006116  ENSG00000182601
1124  ENSG00000077235  ENSG00000171208

[1125 rows x 2 columns]
                    0                1
0     ENSG00000101210  ENSG00000172270
1     ENSG00000099622  ENSG00000141905
2     ENSG00000105278  ENSG00000167658
3     ENSG00000178951  ENSG00000089847
4     ENSG00000141985  ENSG00000127663
...               ...              ...
1120  ENSG00000285395  ENSG00000103316
1121  ENSG00000140740  ENSG00000284218
1122  ENSG00000122254  ENSG00000103365
1123  ENSG00000006116  ENSG00000182601
1124  ENSG00000077235  ENSG000

In [62]:
try:
    masking = list(masking.values())
    layers_node = list(layers_node.values())
except:
    print('already_done')

In [63]:
class TabularDataset(Dataset):
    def __init__(self, count_matrix, label):
        # Read the CSV file
        self.data = count_matrix
        # Separate features and target
        self.features = self.data.values
        self.target = label.values
    
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        # Get features and target for a given index
        features = torch.tensor(self.features[idx], dtype=torch.float32)
        target = torch.tensor(self.target[idx], dtype=torch.float32)
        return features, target

train_dataset = TabularDataset(train_x.T,train_y)
val_dataset = TabularDataset(val_x.T,y_val)
test_dataset = TabularDataset(test_x.T,y_test)

In [64]:
train_dataloader = DataLoader(train_dataset, batch_size=config['train']['batch_size'], shuffle=False)
test_dataloader = DataLoader(test_dataset, batch_size=config['train']['batch_size'], shuffle= False)
val_dataloader = DataLoader(val_dataset, batch_size=config['train']['batch_size'], shuffle= False)

In [65]:
def evaluate(model, dataloader):
    model.eval()  # Set the model to evaluation mode
    correct = 0
    total = 0
    predicted_list = []
    labels_list = []
    criterion = nn.BCEWithLogitsLoss()
    loss = 0
    with torch.no_grad():  # No need to compute gradients during evaluation
        for features, labels in dataloader:
            outputs = model(features)
            print(outputs)
            #print(outputs)
            predicted = torch.round(torch.sigmoid(outputs.data))
            #print(outputs)
            #print(predicted)
            loss += criterion(outputs, labels)
            #_, predicted = torch.sigmoid(outputs.data)
            predicted_list.append(predicted)
            labels_list.append(labels)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    #print(total)
    accuracy = 100 * correct / total
    return accuracy, loss, predicted_list, labels_list

In [66]:
def model_inference(train_dataloader, layers_node, masking, output_layer,model_save_dir):
    
    model = CustomNetwork(layers_node, output_layer, masking)
    model.load_state_dict(torch.load(f'{model_save_dir}best_model_{output_layer}_state_dict.pth'))
    test_accuracy, test_loss, predicted_list_test, labels_list_test = evaluate(model, test_dataloader)
    return test_accuracy, test_loss, predicted_list_test, labels_list_test,model

Current sub-neural network has 1 hidden layers.
tensor([[0.4891],
        [0.4895],
        [0.4897],
        ...,
        [0.4895],
        [0.4888],
        [0.4895]])
tensor([[0.4895],
        [0.4895],
        [0.4901],
        ...,
        [0.4905],
        [0.4883],
        [0.4895]])
tensor([[0.4895],
        [0.4898],
        [0.4895],
        [0.4890],
        [0.4895],
        [0.4900],
        [0.4895],
        [0.4895],
        [0.4888],
        [0.4895],
        [0.4885],
        [0.4897],
        [0.4895],
        [0.4879],
        [0.4895],
        [0.4895],
        [0.4895],
        [0.4900],
        [0.4885],
        [0.4884],
        [0.4895],
        [0.4890],
        [0.4897],
        [0.4895],
        [0.4886],
        [0.4895],
        [0.4886],
        [0.4895],
        [0.4880],
        [0.4895],
        [0.4895],
        [0.4882],
        [0.4898],
        [0.4895],
        [0.4886],
        [0.4878],
        [0.4877],
        [0.4891],
        [0.4895],
      

In [68]:
model

CustomNetwork(
  (layers): ModuleList(
    (0): Linear(in_features=582, out_features=843, bias=False)
    (1): Linear(in_features=843, out_features=1, bias=True)
  )
)

In [71]:
x =model.layers[0].weight.detach().cpu().numpy() 

In [72]:
x

array([[-0.,  0., -0., ..., -0.,  0., -0.],
       [-0., -0.,  0., ...,  0., -0., -0.],
       [-0., -0.,  0., ...,  0., -0., -0.],
       ...,
       [ 0., -0., -0., ..., -0.,  0., -0.],
       [-0., -0.,  0., ..., -0., -0.,  0.],
       [-0., -0.,  0., ...,  0., -0.,  0.]], dtype=float32)

In [73]:
list(x.flatten()).count(0)

490613

In [74]:
len(list(x.flatten()))

490626

In [75]:
config['model_output']['model_save_dir']

'/12tb_dsk1/danish/Pytorch_Biologically_Informed_Neural_Network/model_save/excitory_neurons/Exc_L2-3_CBLN2_LINC02306/'

In [59]:
models = dict()
models_state_dict = dict()
for i in os.listdir(config['model_output']['model_save_dir']+ '2024_07_27_15_17_55'):
    if 'state' in i:
        continue
        
    elif '.pth' in i:
        models[i] = torch.load(config['model_output']['model_save_dir']+ '2024_07_27_15_17_55'+'/' + i)
        k = i.split('.')[0] + '_state_dict.' + i.split('.')[1]
        models_state_dict[i] = torch.load(config['model_output']['model_save_dir']+ '2024_07_27_15_17_55'+'/' + k)

In [80]:
models['best_model_2.pth'].layers[0].weight

Parameter containing:
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0055, 0.0000],
        [0.0000, -0.0000, -0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [-0.0000, -0.0000, -0.0000,  ..., 0.0000, 0.0000, -0.0000],
        ...,
        [-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000,  ..., -0.0000, 0.0000, 0.0000],
        [-0.0000, -0.0000, 0.0000,  ..., 0.0000, 0.0000, -0.0000]],
       requires_grad=True)

In [52]:
model = models['best_model_2.pth']
model

CustomNetwork(
  (layers): ModuleList(
    (0): Linear(in_features=582, out_features=843, bias=False)
    (1): Linear(in_features=843, out_features=1, bias=True)
  )
)

In [81]:
accuracy, loss, predicted_list, labels_list = evaluate(models['best_model_2.pth'], train_dataloader)
accuracy

50.131345402910895

In [19]:
models

NameError: name 'models' is not defined

[array([[1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
   

In [94]:
x = {'a':1,'b':2}

In [96]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
import csv

# Define the model
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 5)
        self.fc2 = nn.Linear(5, 3)
        self.fc3 = nn.Linear(3, 1)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Initialize the model
model = SimpleNN()

# Dictionary to store activations
model_dct = dict()

# Hook function
def hook_fn(module, input, output, layer_name):
    global model_dct
    input_list = [i.detach().cpu().numpy().tolist() for i in input]
    output_list = output.detach().cpu().numpy().tolist()
    
    # If the layer name is not in the dictionary, create a new list for it
    if layer_name not in model_dct:
        model_dct[layer_name] = []

    # Append the activations to the corresponding layer list
    model_dct[layer_name].append({
        'input': input_list,
        'output': output_list
    })

# Register hooks for each layer
for name, layer in enumerate(model.children()):
    layer_name = 'fc'+str(name+1)
    layer.register_forward_hook(lambda module, input, output, name=layer_name: hook_fn(module, input, output, name))

# Create a test dataset and dataloader
# Assuming 100 samples, each of size 10
test_data = torch.randn(100, 10)
test_loader = DataLoader(test_data, batch_size=1, shuffle=False)

# Perform forward pass on each batch in the test loader
for batch in test_loader:
    model(batch)

# Save the activations to a CSV file
with open('model_activations.csv', 'w', newline='') as csvfile:
    fieldnames = ['layer', 'input', 'output']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    
    writer.writeheader()
    for layer_name, activations in model_dct.items():
        for activation in activations:
            writer.writerow({
                'layer': layer_name,
                'input': activation['input'],
                'output': activation['output']
            })

print('Activations saved to model_activations.csv')


Activations saved to model_activations.csv
